FROM nvidia/cuda:11.0-runtime-ubuntu20.04
#FROM nvidia/cuda:11.1-cudnn8-runtime-ubuntu20.04
#FROM nvidia/cuda:11.4.0-cudnn8-runtime-ubuntu20.04
#FROM ubuntu:20.04

#ENV NVIDIA_VISIBLE_DEVICES all
#ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
#ENV NVIDIA_REQUIRE_CUDA "cuda>=11.0 driver>=450"

#RUN export LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64:$LD_LIBRARY_PATH
#RUN export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
RUN apt-get update -y && \
    apt-get install -y python3-pip python3.8-dev
RUN python3 -m pip install --upgrade pip
RUN pip3 install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

# We copy just the requirements.txt first to leverage Docker cache
COPY ../requirements.txt /app/requirements.txt

COPY ../inference.py /app/
COPY ../models/model.py /app/models/
COPY ../checkpoints/model_256_0.171_best.pt /app/checkpoints/
WORKDIR /app

RUN pip3 install -r requirements.txt

ENTRYPOINT [ "python3" ]

CMD [ "inference.py" ]

